### ISSUE TITLE
Internal boost is broken with >=gcc-5.4 and CXX-98

### ISSUE THREAD

**Issue by junghans** [espressopp/espressopp#136]
Our internal boost is too old to support >=gcc-5.4 details see build 5 & 11 of:
https://travis-ci.org/espressopp/espressopp/builds/183276441

**Comment by niktre** [comment]
Do you suggest to update internal boost or to live for a while with uncompiled behavior under some circumstances?

**Comment by junghans** [comment]
At MPI-P is Boost the problem or mpi4py? It seems to me that boost is now so standard that we should basically drop our internal version and ask the users to install the system boost as this will work with their system compiler.

As a plan B let's update the internal version to boost-1.61!

**Comment by niktre** [comment]
Usually the problem is mpi4py. But as far as I know many people compile with INTERNAL boost. Maybe We need an update on that from @acfogarty and @kkreis .

I'm for excluding internal boost from ESPP in mid-term (one year). At the moment, I think we can update internal boost but bring users to compile with external one first (maybe saying it will be somewhat faster with the most modern boost).

**Comment by junghans** [comment]
The main problem with bundling boost is that if you pick a too new version it won't work with legacy machine (that was the case when Espresso++ was started), but if you pick a too old version (current situation) it won't work with recent compilers. And newer compilers are the key to performance.

Due to that reason we have given up on bundling boost with Votca and after an initial phase of complaining by the users it worked out for the better and it saved us a lot of developer cycles.

**Comment by acfogarty** [comment]
> Usually the problem is mpi4py

Agreed.

>  after an initial phase of complaining by the users

Yeah, if I was a non-developer user of espressopp, I would certainly be complaining ;) I use internal boost a lot for convenience.

That said, I don't have any argument for keeping internal boost except user convenience versus developer convenience. 

But before removing internal boost we should check compilation/running with external boost in Garching, Juelich (I can do these but they're offline at the moment) and any other supercomputer anyone else can access.

**Comment by niktre** [comment]
I can compile in Garching and at MPIP with external boost. 

There will be not many complaints from the users, because there are not many users who use ESPP outside of MPIP.

For convenience of normal users we have now docker.

My suggestions are:
1. to keep internal boost for a while, but update it ( @stuehn has a strategy for boost update). 
2. Advise developers and advanced users to build it with external boost. 
3. Advise unexperienced users to get ESPP through docker. 
4. Reduce dependency on boost (use c++ smart pointers etc.) upon Garching team is trying to switch to C++11. Maybe after this happens we can even get rid of boost completely (if it is desired)

**Comment by junghans** [comment]
Updating boost is easy, get all used boost headers:
```
git grep include.*boost -- src | sed -n 's/.*<\(.*\)>.*/\1/p' | sort -u
```
and then use `bcp <header list>`.

**Comment by fedepad** [comment]
@junghans It looks that it takes care of the libraries too, which is good because E++ uses some of the boost stuff that comes as a library (not the only header part). For anyone:
[bcp](http://www.boost.org/doc/libs/1_62_0/tools/bcp/doc/html/index.html)

**Comment by junghans** [comment]
Also #130 (LLNL/spack#2602) should fix the issues at RZG.
