### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by niktre** [espressopp/espressopp#149]
Isn't it confusing that in #143 the sign `#` stays before the opening bracket (why do we need brackets there?) and note before `cores`?

**Comment by junghans** [comment]
This is bikeshedding at its best! Let's just write `-j2` and be done with it!

**Comment by niktre** [comment]
agree

**Comment by acfogarty** [comment]
Any user who's confused by the `#` can just type `make` and be patient :)

On the other hand, I think some other parts of the README still have the potential to be confusing, e.g. now it looks like you have to install docker first. I propose #151

**Comment by junghans** [comment]
I think `-j2` approximately halves the build time, while `-j3` only makes it drop from 50% to 33%, which only a bit better. Plus, espresso++ need a lot of memory to compile due to all the templates and hence `-j4` might be a bit risky on older machines. To me, `-j2` seems a reasonable compromise, and anyhow experienced users see the `-j` flag and will understand that we are supporting parallel builds and know what to do.
