### ISSUE TITLE
H-AdReS setup

### ISSUE THREAD

**Issue by oestrika** [espressopp/espressopp#253]
Hi,

So far I'm able to run a simulation of pure methanol. Now I would would like tu run a HAdReS simulation of a catenan dimer (two knotted loops) in methanol. 
In the ubiquitin example I do not understand why the protein is added twice and how the interatomic interaction can take place on CG level, since in AA region - as I see - there are no CG interactions since the weighting function. So why to do this?

Since the order of adding particles is CG_1 AA_11 AA_12 ... CG_2 ..., first I would Add solvent CG beads wirth coreesponding atoms and then the dimer molecules with a corresponding CG bead in the center of mass (like a virtual site), but without defining interactions for the COM beads. 
Later I would like to adjust two adress centers at the COMs.
So is this possible at all and is there something special I have to mention for doing this?

Best Marco

**Comment by kkreis** [comment]
(1) In adaptive resolution simulations in espresso++, all atomistic particles need to be assigned to a coarse-grained (CG) particle, even if that CG particle is itself not used for any force or energy calculations. In the atomistic region, the ubiquitin interacts with the water on the atomistic level, this is, it interacts with the water molecules' atomistic particles, but not the water molecules' CG beads. Hence, there need to be atomistic particles for the ubiquitin. But as mentioned, CG particles are essentially the "normal" espresso++ particles and in (H-)AdResS simulations all atomistic particles have to be linked to such CG particles. For example, cell- and Verletlists are all built based on the CG particles, not the atomistic particles. That's why there need to be both CG and atomistic particles for the ubiquitin.

(2) I am not familiar with catenane dimers. However, from what I understand there may be different ways to implement this. It sounds like you could implement it similarly like the ubiquitin example and associate both a CG and an atomistic particle with each atom of the dimer. Separate from that you can then set the atomistic region using a fixed coordinate or using one or two extra, fixed CG particles (in the center or the two centers of the dimer) that do not interact with anything, but are only present to define the atomistic region.

Alternatively, you could also define the dimers only as atomistic particles and associate them with only one or two individual CG particles in the middle. But be aware that, as I said before, cell- and Verletlists are built based on the CG, not the atomistic particles and that this would probably require impractically large Verletlist buffers, because the interacting atomistic particles would be far away from their CG bead. Also, you don't want your atomistic region center(s) to move around when running H-AdResS, in case you use the central CG bead(s) also to define the atomistic region. 

Furthermore, note that you may run into problems when having an irregularly shaped atomistic region (for example, via two overlapping spheres) in H-AdResS, because of the drift force term in H-AdResS. This would be possible in regular force-based AdResS. Alternatively, you can just make one large spherical atomistic region that includes the whole object.

Also see http://www.espresso-pp.de/Documentation/tutorial.AdResS.html
