### ISSUE TITLE
Compute of LJ potential cause NaN

### ISSUE THREAD

**Issue by MrTheodor** [espressopp/espressopp#36]
It is somehow related to the discussion under #31 about Array2D. Mainly this piece of code will fail because `LJ._computeForceRaw` will get `distSqr = 0` and it will return force NaN.
The very simple solution is to have a flag in `Potential.hpp` (initialized) that by default will be set to `false` and only if potential object is constructed with proper parameters it will be changed to `true`. Force and energy would be computed only if this flag is set to `true`. Or, changes in `Array2D` so that for a non-defined potential it will use Zero potential.

``` python
import espressopp  # pylint:disable=F0401

try:
    import MPI  # pylint: disable=F0401
except ImportError:
    from mpi4py import MPI

box = (10.0, 10.0, 10.0)
skin = 0.3
rc = 2.5
dt = 0.0025

system = espressopp.System()
system.rng = espressopp.esutil.RNG()
system.bc = espressopp.bc.OrthorhombicBC(system.rng, box)
system.skin = skin
nodeGrid = espressopp.tools.decomp.nodeGrid(MPI.COMM_WORLD.size)
cellGrid = espressopp.tools.decomp.cellGrid(box, nodeGrid, rc, skin)
print(nodeGrid, cellGrid)
system.storage = espressopp.storage.DomainDecomposition(system, nodeGrid, cellGrid)
integrator = espressopp.integrator.VelocityVerlet(system)
integrator.dt = dt

particles = [
 (0, espressopp.Real3D(2, 2, 2), 0),
 (1, espressopp.Real3D(2, 2, 2), 1),  # this overlap
 (2, espressopp.Real3D(3, 2, 2), 0)
 ]
system.storage.addParticles(particles, 'id', 'pos', 'type')

system.storage.decompose()
verletlist = espressopp.VerletList(system, cutoff=1.16)
lj = espressopp.interaction.VerletListLennardJones(verletlist)
# Only interaction between types: 0 and 0
lj.setPotential(type1=0, type2=0, potential=espressopp.interaction.LennardJones(sigma=1.0, epsilon=1.0, cutoff=1.16))
system.addInteraction(lj)

for i in range(2):
    print system.storage.getParticle(1).f
    espressopp.tools.analyse.info(system, integrator)
    integrator.run(10)
```

**Comment by vitst** [comment]
I guess it will slow down the loop.

**Comment by niktre** [comment]
@vitst what exactly do you mean? :-) that the ```bool``` flag will slow it down or changes in ```Array2D```?

Since I had a similar issue with LJ-cos potential, I would suggest one has to think on global changes to ```Array2D```...

**Comment by vitst** [comment]
I mean the flag because it is within the loop. However it is easy to check. Just do the change and compare times. I'm not sure though how you would fix it in Array2D.

**Comment by fedepad** [comment]
So I think it's related somehow to this stuff and #31 . In OSX 10.11.4 and Apple LLVM version 7.3.0 (clang-703.0.31) , with latest master one of the tests fails (while doesn't fail on my Linux...).

Does somebody else developing also on OSX sees similar thing?
Here the log for the test; odd because I don't know why it passes on Linux and clang on Linux (Travis) but not in my OSX.

9/18 Testing: fixed_list_types_test
9/18 Test: fixed_list_types_test
Command: "/Users/padua/.virtualenvs/espressopp_virtualenv/bin/python2" "/Users/padua/work_projects/espressopp/testsuite/fixed_list_types_test/fixed_list_types_test.py"
Directory: /Users/padua/work_projects/espressopp/build/testsuite/fixed_list_types_test
"fixed_list_types_test" start time: Oct 09 21:02 CEST
Output:
----------------------------------------------------------
FWarning! computeVirial in FixedPairListTypesInteractionTemplate has not been tested.
Warning! computeVirial in FixedPairListTypesInteractionTemplate has not been tested.
......F..
======================================================================
FAIL: test_check_energy (__main__.TestFixedPairListTypesTabulated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/padua/work_projects/espressopp/testsuite/fixed_list_types_test/fixed_list_types_test.py", line 79, in test_check_energy
    self.assertEqual(self.interaction.computeEnergy(), 3.0)
AssertionError: nan != 3.0

======================================================================
FAIL: test_check_energy (__main__.TestFixedTripleListTypesTabulated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/padua/work_projects/espressopp/testsuite/fixed_list_types_test/fixed_list_types_test.py", line 140, in test_check_energy
    self.assertAlmostEqual(self.interaction.computeEnergy(), 1.0)  # contribution from table a1
AssertionError: nan != 1.0 within 7 places

----------------------------------------------------------------------
Ran 10 tests in 0.031s

FAILED (failures=2)
<end of output>
Test time =   0.28 sec
----------------------------------------------------------
Test Failed.
"fixed_list_types_test" end time: Oct 09 21:02 CEST
"fixed_list_types_test" time elapsed: 00:00:00

**Comment by niktre** [comment]
@fedepad I confirm that it comes to this comparison of `nan` with a number. OS X 10.12 and Apple LLVM version 8.0.0 (clang-800.0.38).

But if you run this test 10-20 times you'll notice that sometimes it finished ok:
```
niktre@MacBook-Pro-3:~/Software/myFork_espressopp/testsuite/fixed_list_types_test$ python fixed_list_types_test.py 
.Warning! computeVirial in FixedPairListTypesInteractionTemplate has not been tested.
Warning! computeVirial in FixedPairListTypesInteractionTemplate has not been tested.
.........
----------------------------------------------------------------------
Ran 10 tests in 0.039s

OK
```

**Comment by fedepad** [comment]
@niktre Thanks, your feedback is very appreciated!!! 
Because I've been getting that for a while on OSX but I haven't reported seeing that in Linux passes.
Good to know, since all the times I've run has always failed for me ;) I'll try like 20 on a row sometimes!
