### ISSUE TITLE
polymer_melt_tabulated_thirdcell is not a test...

### ISSUE THREAD

**Issue by XzzX** [espressopp/espressopp#382]
`82/82 Test #80: polymer_melt_tabulated_thirdcell .....   Passed  3103.93 sec`

This test runs for 51 minutes in debug mode. That is not a test. @jnvance Can we make this faster or move it to exampeles?

**Comment by jnvance** [comment]
I've sped up the test by using `addParticles` and reducing the steps to 10.

I'm also not sure if the polymer melt test case for halfCellInt=3 is useful since particles/cell = 0.09. Even at halfCellInt=2, particles/cell = 0.32 so most cells are completely empty. IIRC, the half-cell method was developed in MPCDF.

**Comment by govarguz** [comment]
@jnvance, well the half-cell method was developed time before, already and in other codes. I was pointing out pavel from MPCDF to implement it as well as thirdCells or any type of cells. However, it is just a flag not big implementation. As for testing, yes thridCells might not be useful and to test the functionality halfCells may suffice

**Comment by jnvance** [comment]
@govarguz I should've said "implemented", thanks for clarifying :)

We should just remove thirdCells for this test then.

**Comment by govarguz** [comment]
Yes, the same flag is used for halfs, thirds, quarters and so on... Halfcells should be OK. If we want to increase the Particles/Cells we could play with the cutoff on those tests but as they are short it won't make a difference.
