### ISSUE TITLE
mpi4py-2 breaks Espresso++

### ISSUE THREAD

**Issue by junghans** [espressopp/espressopp#51]
We using a newer mpi4py version (0e356b00e444b4c550489bff54893c348e900e22) stuff breaks, see:
<https://travis-ci.org/espressopp/espressopp/jobs/107627162>

Error:
```
ValueError: too many values to unpack
```

**Comment by fedepad** [comment]
@junghans I can confirm this failing test caused by that bug on OSX too with mpi4py version 2.0.0
I'll also have to mention that basically all tests fail on the same machine, so I don't know how they passed the Travis tests, even the recent ones, with the new mpi4py version (2.0.0)... 
We have to make sure no tests are failing with the old mpi4py (travis right?).
I refer for example to: FreeEnergyCompensation, HAdResS, ForceAdResS and thermo_integration just to mention the most recent ones.
I think I found the problem. 
Now all tests pass (except fixed_list_types_test, which was failing before too due to other reasons).
I will open a pull request, I want to discuss there some stuff about this.

**Comment by junghans** [comment]
Travis installed mpi4py 1.3.1 using
```
pip install --user mpi4py==1.3.1
```
